# Generated by Django 5.2.7 on 2025-10-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.AddField(
            model_name='turma',
            name='codigo_acesso',
            field=models.CharField(default=0, help_text='Senha para o professor acessar a turma.', max_length=50),
            preserve_default=False,
        ),
    ]
