# Generated by Django 5.2.7 on 2025-10-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebd', '0002_remove_turma_professor_turma_codigo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='alunos_com_biblia',
            field=models.ManyToManyField(blank=True, related_name='biblias', to='ebd.aluno'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='alunos_com_licao',
            field=models.ManyToManyField(blank=True, related_name='licoes', to='ebd.aluno'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='oferta_do_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamada',
            name='visitantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='alunos_presentes',
            field=models.ManyToManyField(blank=True, related_name='presencas', to='ebd.aluno'),
        ),
    ]
