# Generated by Django 5.2.7 on 2025-10-13 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebd', '0003_chamada_alunos_com_biblia_chamada_alunos_com_licao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamada',
            name='alunos_com_biblia',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='alunos_com_licao',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='alunos_presentes',
        ),
        migrations.CreateModel(
            name='RegistroAlunoChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('trouxe_biblia', models.BooleanField(default=False)),
                ('trouxe_revista', models.BooleanField(default=False)),
                ('contribuiu', models.BooleanField(default=False)),
                ('levou_visitante', models.BooleanField(default=False)),
                ('participacao', models.CharField(choices=[('NADA', 'Nada'), ('MEDIANO', 'Mediano'), ('MUITO', 'Muito')], default='NADA', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebd.aluno')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebd.chamada')),
            ],
            options={
                'unique_together': {('chamada', 'aluno')},
            },
        ),
    ]
