# Generated by Django 5.2.7 on 2025-10-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebd', '0004_remove_chamada_alunos_com_biblia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
